name: iOS-ipa-build
on:
  workflow_dispatch:
jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
          
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
      
      - name: Flutter version
        run: flutter --version
      
      # Sửa lỗi plugin thiếu  
      - name: Add missing device_info_plus explicitly
        run: flutter pub add device_info_plus
      
      - name: Display plugin status
        run: |
          echo "PLUGINS IN PUBSPEC.YAML:"
          grep -A 20 "dependencies:" pubspec.yaml
          echo "--------"
          flutter pub deps | grep device_info
      
      # Xóa tất cả các tệp iOS để tạo lại từ đầu  
      - name: Clean iOS files completely
        run: |
          rm -rf ios
          rm -rf .ios
          flutter create --platforms=ios .
      
      # Tạo Podfile mới và thêm plugin   
      - name: Create Podfile
        run: |
          cd ios
          if [ -f "Podfile" ]; then
            echo "Podfile exists, updating..."
            # Sửa platform version trong Podfile
            sed -i '' 's/# platform :ios.*/platform :ios, '"'"'13.0'"'"'/g' Podfile
            # Nếu không tìm thấy dòng platform, thêm mới
            if ! grep -q "platform :ios" Podfile; then
              sed -i '' '1s/^/platform :ios, '"'"'13.0'"'"'\n/' Podfile
            fi
            cat Podfile # Hiển thị nội dung Podfile sau khi sửa
            flutter pub get
            pod install --repo-update
          else
            echo "Podfile not found, creating..."
            flutter pub get
            pod init
            # Thêm platform iOS version
            sed -i '' '1s/^/platform :ios, '"'"'13.0'"'"'\n/' Podfile
            echo "post_install do |installer|" >> Podfile
            echo "  installer.pods_project.targets.each do |target|" >> Podfile
            echo "    flutter_additional_ios_build_settings(target)" >> Podfile
            echo "    target.build_configurations.each do |config|" >> Podfile
            echo "      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'" >> Podfile
            echo "    end" >> Podfile
            echo "  end" >> Podfile
            echo "end" >> Podfile
            cat Podfile # Hiển thị nội dung Podfile
            pod install --repo-update
          fi
            
      # Kiểm tra GeneratedPluginRegistrant.m
      - name: Check GeneratedPluginRegistrant.m
        run: |
          echo "CONTENT OF GeneratedPluginRegistrant.m:"
          cat ios/Runner/GeneratedPluginRegistrant.m || echo "File not found"
      
      # Sửa GeneratedPluginRegistrant.m nếu cần
      - name: Fix GeneratedPluginRegistrant.m if needed
        run: |
          if grep -q "device_info_plus" ios/Runner/GeneratedPluginRegistrant.m; then
            echo "device_info_plus found in GeneratedPluginRegistrant.m"
          else
            echo "device_info_plus not found in GeneratedPluginRegistrant.m, fixing..."
            echo "Adding device_info_plus to project..."
            cd ios
            pod repo update
            pod install --repo-update
          fi
      
      # Kiểm tra Podfile
      - name: Check Podfile content
        run: |
          echo "CONTENT OF PODFILE:"
          cat ios/Podfile || echo "Podfile not found"
          echo "CONTENT OF PODFILE.LOCK:"
          cat ios/Podfile.lock || echo "Podfile.lock not found"
      
      - name: Flutter build iOS
        run: flutter build ios --release --no-codesign
      
      - name: Create Payload directory
        run: mkdir Payload
        working-directory: build/ios/iphoneos
      
      - name: Move Runner.app to Payload
        run: mv Runner.app Payload
        working-directory: build/ios/iphoneos
      
      - name: Zip output
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos
      
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is first release"
