name: iOS-ipa-build
on:
  workflow_dispatch:
jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
          
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
      
      - name: Flutter version
        run: flutter --version

      - name: Display pubspec.yaml
        run: cat pubspec.yaml
      
      - name: Flutter pub get
        run: flutter pub get
        
      - name: Debug - List dependencies
        run: flutter pub deps
        
      - name: Debug - Check for device_info_plus
        run: flutter pub deps | grep -i device_info

      - name: Flutter clean
        run: flutter clean
        
      - name: Flutter pub get (again after clean)
        run: flutter pub get
        
      - name: Verify iOS directory structure
        run: |
          ls -la ios/
          ls -la ios/Runner/
          cat ios/Runner/GeneratedPluginRegistrant.m || echo "GeneratedPluginRegistrant.m not found"
      
      - name: Force regenerate plugin registrant
        run: |
          rm -rf ios/Flutter/Flutter.podspec || true
          flutter create --platforms=ios . --org com.example

      - name: Install CocoaPods dependencies with verbose output
        run: |
          cd ios
          pod repo update
          rm -rf Pods Podfile.lock
          pod install --verbose
      
      - name: Add missing device_info_plus if needed
        run: |
          if ! grep -q "device_info_plus" pubspec.yaml; then
            echo "device_info_plus not found in pubspec.yaml, adding it"
            flutter pub add device_info_plus
          fi
      
      - name: Flutter build iOS
        run: flutter build ios --release --no-codesign
      
      - name: Create Payload directory
        run: mkdir Payload
        working-directory: build/ios/iphoneos
      
      - name: Move Runner.app to Payload
        run: mv Runner.app Payload
        working-directory: build/ios/iphoneos
      
      - name: Zip output
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos
      
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is first release"
